dog_v4:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  LF_top_position_controller:
    type: effort_controllers/JointPositionController
    joint: LF_top_joint
    pid: {p: 10000.0, i: 0.01, d: 10.0}

  LF_mid_position_controller:
    type: effort_controllers/JointPositionController
    joint: LF_mid_joint
    pid: {p: 10000.0, i: 0.01, d: 10.0}

  LF_down_position_controller:
    type: effort_controllers/JointPositionController
    joint: LF_down_joint
    pid: {p: 10000.0, i: 0.01, d: 10.0}


  RF_top_position_controller:
    type: effort_controllers/JointPositionController
    joint: RF_top_joint
    pid: {p: 10000.0, i: 0.01, d: 10.0}

  RF_mid_position_controller:
    type: effort_controllers/JointPositionController
    joint: RF_mid_joint
    pid: {p: 10000.0, i: 0.01, d: 10.0}

  RF_down_position_controller:
    type: effort_controllers/JointPositionController
    joint: RF_down_joint
    pid: {p: 10000.0, i: 0.01, d: 10.0}
  
  LB_top_position_controller:
    type: effort_controllers/JointPositionController
    joint:  LB_top_joint
    pid: {p: 10000.0, i: 0.01, d: 10.0}

  LB_mid_position_controller:
    type: effort_controllers/JointPositionController
    joint: LB_mid_joint
    pid: {p: 10000.0, i: 0.01, d: 10.0}

  LB_down_position_controller:
    type: effort_controllers/JointPositionController
    joint:  LB_down_joint
    pid: {p: 10000.0, i: 0.01, d: 10.0}

  RB_top_position_controller:
    type: effort_controllers/JointPositionController
    joint: RB_top_joint
    pid: {p: 10000.0, i: 0.01, d: 10.0}

  RB_mid_position_controller:
    type: effort_controllers/JointPositionController
    joint: RB_mid_joint
    pid: {p: 10000.0, i: 0.01, d: 10.0}
    
  RB_down_position_controller:
    type: effort_controllers/JointPositionController
    joint: RB_down_joint
    pid: {p: 10000.0, i: 0.01, d: 10.0}
