(cl:in-package unitree_legged_msgs-msg)
(cl:export '(LEVELFLAG-VAL
          LEVELFLAG
          COMMVERSION-VAL
          COMMVERSION
          ROBOTID-VAL
          ROBOTID
          SN-VAL
          SN
          BANDWIDTH-VAL
          BANDWIDTH
          MODE-VAL
          MODE
          PROGRESS-VAL
          PROGRESS
          IMU-VAL
          IMU
          GAITTYPE-VAL
          GAITTYPE
          FOOTRAISEHEIGHT-VAL
          FOOTRAISEHEIGHT
          POSITION-VAL
          POSITION
          BODYHEIGHT-VAL
          BODYHEIGHT
          VELOCITY-VAL
          VELOCITY
          YAWSPEED-VAL
          YAWSPEED
          FOOTPOSITION2BODY-VAL
          FOOTPOSITION2BODY
          FOOTSPEED2BODY-VAL
          FOOTSPEED2BODY
          BMS-VAL
          BMS
          FOOTFORCE-VAL
          FOOTFORCE
          FOOTFORCEEST-VAL
          FOOTFORCEEST
          WIRELESSREMOTE-VAL
          WIRELESSREMOTE
          RESERVE-VAL
          RESERVE
          CRC-VAL
          CRC
))